[connection.snowflake]
account = "NMDNKEE-LY58078"
user = "JoelDreskin"
password = "SnowD00dle!"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
