[connections.snowflake]
account = "NMDNKEE-LY58078"
user = "JOELDRESKIN"
password = "SnowD00dle!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
